language: node_js
node_js:
- lts/*

addons:
  ssh_known_hosts: huajingkun.com

before_install:
- git clone --depth=1 --branch=hexo https://github.com/hjkcai/blog.git __hexo && cd __hexo
- git submodule update --init --recursive
- bash .travis/before_install.sh

script:
- yarn run build

after_success:
- bash .travis/after_success.sh

cache: yarn
