language: node_js
node_js:
- lts/*

addons:
  ssh_known_hosts: huajingkun.com

before_install:
- bash .travis/before_install.sh

script:
- yarn run build

after_success:
- bash .travis/after_success.sh

cache: yarn
