language: node_js
node_js:
- node

addons:
  ssh_known_hosts: huajingkun.com

before_install:
- bash build/before_install.sh

script:
- yarn run build

after_success:
- bash build/after_success.sh

cache: yarn
